#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Entry-point script for the Configuration Integrity Runner.

.DESCRIPTION
    Loads desired and actual state files, runs drift detection, scores the result,
    writes a JSON report, and exits with a non-zero code if the score falls below
    the threshold (useful as a CI gate).

.PARAMETER DesiredStatePath
    Path to the desired-state JSON file.

.PARAMETER ActualStatePath
    Path to the actual-state JSON file. In production this would be
    generated by an Az CLI or Azure PowerShell discovery script.

.PARAMETER OutputPath
    Where to write the JSON report. Defaults to ./output/integrity-report.json

.PARAMETER PassThreshold
    Minimum score (0-100) to exit 0. Defaults to 80.

.PARAMETER FailOnCriticalDrift
    If set, exits non-zero whenever any Critical-severity resource has drift,
    regardless of overall score.

.EXAMPLE
    ./Invoke-IntegrityRunner.ps1 `
        -DesiredStatePath ./sample-data/desired-state.json `
        -ActualStatePath  ./sample-data/actual-state.json  `
        -OutputPath       ./sample-output/report.json      `
        -PassThreshold    85
#>
[CmdletBinding()]
param(
    [string]$DesiredStatePath = "$PSScriptRoot/sample-data/desired-state.json",
    [string]$ActualStatePath  = "$PSScriptRoot/sample-data/actual-state.json",
    [string]$OutputPath       = "$PSScriptRoot/sample-output/integrity-report.json",
    [ValidateRange(0,100)]
    [double]$PassThreshold    = 80.0,
    [switch]$FailOnCriticalDrift
)

$ErrorActionPreference = 'Stop'

# --- Bootstrap ---
$modulePath = Join-Path $PSScriptRoot 'src/ConfigIntegrityRunner.psm1'
Import-Module $modulePath -Force

# --- Ensure output directory exists ---
$outputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# --- Run ---
Write-Host "Loading desired state from: $DesiredStatePath"
$desired = Import-DesiredState -Path $DesiredStatePath

Write-Host "Loading actual state from:  $ActualStatePath"
$actual = Import-ActualState -Path $ActualStatePath

Write-Host "Running integrity checks..."
$runResult = Invoke-ConfigIntegrityCheck `
    -DesiredState     $desired `
    -ActualState      $actual `
    -DesiredStatePath $DesiredStatePath `
    -ActualStatePath  $ActualStatePath

# --- Print console summary ---
Export-IntegrityReport -RunResult $runResult -OutputPath $OutputPath -ConsoleSummary

# --- ServiceNow payload preview ---
$snowPayload = ConvertTo-ServiceNowPayload -RunResult $runResult
$snowJson = $snowPayload | ConvertTo-Json -Depth 8
$snowOutputPath = Join-Path (Split-Path $OutputPath -Parent) 'servicenow-payload.json'
$snowJson | Set-Content -Path $snowOutputPath -Encoding UTF8
Write-Host ""
Write-Host "ServiceNow payload written to: $snowOutputPath" -ForegroundColor Cyan

# --- CI Gate ---
$exitCode = 0

if ($runResult.Score -lt $PassThreshold) {
    Write-Host ""
    Write-Warning "INTEGRITY SCORE $($runResult.Score) IS BELOW THRESHOLD $PassThreshold — failing run."
    $exitCode = 1
}

if ($FailOnCriticalDrift -and $runResult.Summary.CriticalDrift -gt 0) {
    Write-Host ""
    Write-Warning "CRITICAL DRIFT DETECTED ($($runResult.Summary.CriticalDrift) rule(s)) — failing run."
    $exitCode = 1
}

if ($exitCode -eq 0) {
    Write-Host ""
    Write-Host "Integrity gate PASSED (score $($runResult.Score), threshold $PassThreshold)." -ForegroundColor Green
}

exit $exitCode
